
services:

  # Toolbox client App
  toolbox-client:
    env_file: 
      - path: ./docker.env
        required: true # default
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run toolbox-client:dev:docker
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}

  # Auth App
  auth:
    env_file: 
      - path: ./docker.env
        required: true # default
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run auth:dev:docker
    depends_on:
      - mongo
    ports:
      -  ${AUTH_HTTP_PORT}:${AUTH_HTTP_PORT}

  # Books ms
  books:
    env_file: 
      - path: ./docker.env
        required: true # default
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run books:dev:docker
    depends_on:
      - mongo

  toolbox-gateway:
    env_file: 
      - path: ./docker.env
        required: true # default
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run toolbox-gateway:dev:docker
    ports:
      -  ${GATEWAY_PORT}:${GATEWAY_PORT} 

  mongo:
    image: mongo

volumes:
  mono-node-modules: null
